In [38]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [39]:
df=pd.read_csv("/content/train file.txt", sep=';', header=None, names=['text','emotion'])

In [40]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [41]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [42]:
df['emotion'].unique()

array(['sadness', 'anger', 'love', 'surprise', 'fear', 'joy'],
      dtype=object)

In [43]:
emotion_counts=df['emotion'].value_counts()
emotion_counts

emotion
joy         5362
sadness     4666
anger       2159
fear        1937
love        1304
surprise     572
Name: count, dtype: int64

In [44]:
unique_emotions = df['emotion'].unique()
emotions_numbers = {}
i = 0
for emo in unique_emotions:
  emotions_numbers[emo] = i
  i += 1
df['emotion'] = df['emotion'].map(emotions_numbers)

In [45]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

**Text Cleaning**

In [46]:
df['text']= df['text'].apply(lambda x: x.lower())

In [47]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

**Removing Punctuation**

In [48]:
import string
def remove_punc(txt):
  return txt.translate(str.maketrans('','',string.punctuation))

In [49]:
df["text"]=df["text"].apply(remove_punc)

**Removing Numbers**

In [50]:
def remove_numbers(txt):
    new = ""
    for i in txt:
        if not i.isdigit():
            new = new + i
    return new

df["text"] = df["text"].apply(remove_numbers)

**Remove Emoji**

In [51]:
def remove_emojis(txt):
  new=""
  for i in txt:
    if i.isascii():
      new=new+i
    return new

  df["text"]=df["text"].apply(remove_emojis)

**Remove Stopwords**

In [52]:
import nltk

In [53]:
# len(stop_words)

In [54]:
df.loc[1]["text"]

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [55]:
#now remove stop words from text

def remove(txt):
  #words=word_tokenize(txt)
  words=txt.split()
  cleaned=[]
  for i in words:
    if not i in stop_words:
      cleaned.appened(i)
    return" ".join(cleaned)

In [56]:
# Now remove stop words from text

def remove(txt):

    # words = word_tokenize(txt)
    words = txt.split()

    cleaned = []

    for i in words:
        if i not in stop_words:
            cleaned.append(i)

    return " ".join(cleaned)

In [57]:
import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')

stop_words = set(stopwords.words('english'))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [58]:
def remove(txt):

    words = txt.split()
    cleaned = []

    for i in words:
        if i not in stop_words:
            cleaned.append(i)

    return " ".join(cleaned)

In [59]:
df["text"] = df["text"].apply(remove)

In [60]:
df.loc[1]["text"]

'go feeling hopeless damned hopeful around someone cares awake'

In [61]:
# i can go feeling hopeless damned hopeful around someone cares awake.

In [62]:
df.head()

                                                text  emotion
0                              didnt feel humiliated        0
1  go feeling hopeless damned hopeful around some...        0
2          im grabbing minute post feel greedy wrong        1
3  ever feeling nostalgic fireplace know still pr...        2
4                                    feeling grouchy        1

In [63]:
df.shape

(16000, 2)

In [64]:
from sklearn.model_selection import train_test_split

In [65]:
x=df["text"]
y=df["emotion"]

In [66]:
x

0                                    didnt feel humiliated
1        go feeling hopeless damned hopeful around some...
2                im grabbing minute post feel greedy wrong
3        ever feeling nostalgic fireplace know still pr...
4                                          feeling grouchy
                               ...
15995        brief time beanbag said anna feel like beaten
15996    turning feel pathetic still waiting tables sub...
15997                             feel strong good overall
15998                       feel like rude comment im glad
15999                         know lot feel stupid portray
Name: text, Length: 16000, dtype: object

In [67]:
y

0        0
1        0
2        1
3        2
4        1
        ..
15995    0
15996    0
15997    5
15998    1
15999    0
Name: emotion, Length: 16000, dtype: int64

In [68]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

In [69]:
x_train

676      refers course though cant help feeling somehow...
12113                im starting feel im suffering fatigue
7077     feel like probably would liked book little bit...
13005                                  really feel awkward
12123    im feeling little grumpy today lame weather te...
                               ...
13418    love leave reader feeling confused slightly de...
5390                                         feel delicate
860                          starting feel little stressed
15795             feel stressed tired worn shape neglected
7270         feel someone rude wrongly done something lose
Name: text, Length: 12800, dtype: object

In [70]:
y_train

676      5
12113    0
7077     2
13005    0
12123    1
        ..
13418    4
5390     2
860      0
15795    0
7270     1
Name: emotion, Length: 12800, dtype: int64

In [71]:
x_test

8756                             ive made week feel beaten
4660                              feel strategy worthwhile
6095                     feel worthless weak say want find
304                                        feel clever nov
8241                      im moved ive feeling kind gloomy
                               ...
15578    feel useful pulpit find ironic often question ...
5746             dried bladders ready day im feeling brave
6395                             feel thrilled matter days
7624     woke morning text mr c declaring walking work ...
15245                                            feel dumb
Name: text, Length: 3200, dtype: object

In [72]:
# Converting text into vectoriize forms

In [73]:
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer

In [74]:
bow_vectorizer=CountVectorizer()
tfidf_vectorizer=TfidfVectorizer()

In [75]:
x_train_bow=bow_vectorizer.fit_transform(x_train)
x_test_bow=bow_vectorizer.transform(x_test)

In [76]:
x_train_bow

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 116059 stored elements and shape (12800, 13361)>

In [77]:
x_test_bow

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 26936 stored elements and shape (3200, 13361)>

In [78]:
# Now we implimenting ML

In [79]:
#Applying Multinomial Naive Bayes

from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

In [80]:
# nb_model=MultinomialNB()
# nb_model.fit(x_train_bow,y_train)

In [81]:
# pred=nb_model.predict(x_test_bow)

In [82]:
# print(accuracy_score(y_test,pred))
# print(classification_report(y_test,pred))

In [83]:
# now do it with Logistic regression

In [84]:
# project name: sentiment Analysis project......

In [85]:
# 2 sept

## ** Applying Logistic Regression**

In [86]:
# Now we are implementing ML



# from sklearn.linear_model import LogisticRegression
# from sklearn.metrics import accuracy_score, classification_report

# # Create Logistic Regression model
# lr_model = LogisticRegression()

# # Train the model
# lr_model.fit(x_train_bow, y_train)

# # Make predictions
# pred = lr_model.predict(x_test_bow)

# # Check accuracy
# print(accuracy_score(y_test, pred))

# # Classification report
# print(classification_report(y_test, pred))

## **Applying TF-IDF**

### **Applying Naive Bayes for TF-IDF**

In [98]:
tfidf_vectorizer=TfidfVectorizer()
x_train_tfidf=tfidf_vectorizer.fit_transform(x_train)
x_test_tfidf=tfidf_vectorizer.transform(x_test)

In [88]:
# Applying Naive Bayes ML Model

In [89]:
# nb_model_2=MultinomialNB()
# nb_model_2.fit(x_train_tfidf,y_train)

In [90]:
# pred=nb_model_2.predict(x_test_tfidf)

In [91]:
# print(accuracy_score(y_test, pred))

In [92]:
# print(classification_report(y_test, pred))

### **# Applying Logistic Regression for TF-IDF**

In [93]:
# Applying Logistic Regression for TF-IDF

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

In [94]:
# Create Logistic Regression model
lr_model = LogisticRegression()

In [99]:
# Train the model
lr_model.fit(x_train_tfidf, y_train)

LogisticRegression()

In [100]:
# Make predictions
pred_lr = lr_model.predict(x_test_tfidf)

In [101]:
# Check accuracy
print(accuracy_score(y_test, pred_lr))

0.8628125

In [103]:

# classification report
print(classification_report(y_test, pred_lr))

              precision    recall  f1-score   support

           0       0.90      0.94      0.92       946
           1       0.90      0.81      0.86       427
           2       0.90      0.61      0.73       296
           3       0.88      0.47      0.61       113
           4       0.86      0.76      0.81       397
           5       0.81      0.96      0.88      1021

    accuracy                           0.86      3200
   macro avg       0.88      0.76      0.80      3200
weighted avg       0.87      0.86      0.86      3200

## **Predicting Sentiment on User Input**

In [109]:
def preprocess_input(text):
    # Apply the same preprocessing steps as applied to the training data
    text = text.lower()
    text = remove_punc(text)
    text = remove_numbers(text)
    # The remove_emojis function in the notebook returns only the first character,
    # so we'll use a more robust one or ensure the original works as intended.
    # For now, let's assume it was intended to remove non-ascii characters properly.
    # Re-defining a simple version here that ensures it processes the whole string.
    new_text = ""
    for char in text:
        if char.isascii():
            new_text += char
    text = new_text
    text = remove(text) # Assuming 'remove' function is for stopwords
    return text

user_input = input("Enter text to predict its sentiment: ")

# Preprocess the user input
cleaned_input = preprocess_input(user_input)

# Transform the preprocessed input using the loaded TF-IDF vectorizer
user_input_tfidf = tfidf_vectorizer.transform([cleaned_input])

# Predict sentiment using the trained Logistic Regression model
lr_prediction = lr_model.predict(user_input_tfidf)[0]

# Reverse the emotion_numbers dictionary to map numbers back to emotion names
# This dictionary (number_to_emotion) was available in the kernel state.
# number_to_emotion = {v: k for k, v in emotions_numbers.items()}

# Map numerical prediction back to emotion name
lr_emotion = number_to_emotion.get(lr_prediction, "Unknown")

print(f"\nInput Text: {user_input}")
print(f"Cleaned Text: {cleaned_input}")
print(f"Predicted Emotion (Logistic Regression - TF-IDF): {lr_emotion}")

Enter text to predict its sentiment: i am angry

Input Text: i am angry
Cleaned Text: angry
Predicted Emotion (Logistic Regression - TF-IDF): anger

## **Saving Models and Vectorizers**

In [110]:
import joblib

# Define filenames for the models and vectorizers
lr_model_tfidf_filename = 'logistic_regression_tfidf_model.joblib'
tfidf_vectorizer_filename = 'tfidf_vectorizer.joblib'

# Save the Logistic Regression model (trained with TF-IDF)
joblib.dump(lr_model, lr_model_tfidf_filename)
print(f'Logistic Regression (TF-IDF) model saved as {lr_model_tfidf_filename}')

# Save the TF-IDF Vectorizer
joblib.dump(tfidf_vectorizer, tfidf_vectorizer_filename)
print(f'TF-IDF Vectorizer saved as {tfidf_vectorizer_filename}')

print('\nVerifying created files:')
!ls -l *.joblib

Logistic Regression (TF-IDF) model saved as logistic_regression_tfidf_model.joblib
TF-IDF Vectorizer saved as tfidf_vectorizer.joblib

Verifying created files:
-rw-r--r-- 1 root root 642263 Sep  5 07:12 logistic_regression_tfidf_model.joblib
-rw-r--r-- 1 root root 281717 Sep  5 07:12 tfidf_vectorizer.joblib

## **Loading Saved Models and Vectorizers**

In [111]:
import joblib

# Define filenames (should be the same as used for saving)
lr_model_tfidf_filename = 'logistic_regression_tfidf_model.joblib'
tfidf_vectorizer_filename = 'tfidf_vectorizer.joblib'

# Load the Logistic Regression model (TF-IDF)
loaded_lr_model_tfidf = joblib.load(lr_model_tfidf_filename)
print(f'Logistic Regression (TF-IDF) model loaded from {lr_model_tfidf_filename}')

# Load the TF-IDF Vectorizer
loaded_tfidf_vectorizer = joblib.load(tfidf_vectorizer_filename)
print(f'TF-IDF Vectorizer loaded from {tfidf_vectorizer_filename}')

print('\nLoaded model and vectorizer are ready for use!')

Logistic Regression (TF-IDF) model loaded from logistic_regression_tfidf_model.joblib
TF-IDF Vectorizer loaded from tfidf_vectorizer.joblib

Loaded model and vectorizer are ready for use!